[workspace]
resolver = "2"

members = [
    "fat_badges",
    "easy_oracle",
    "advanced_judger",
    "twitter_oracle",
    "utils",
    "utils/environmental",
]

exclude = [
    "vendor/openbrush-contracts",
]
